Fix GH32:  Linux Mint built added.
Now one function per distribution/version, except for Fedora.

diff --git a/packages/package-create b/packages/package-create
--- a/packages/package-create
+++ b/packages/package-create
@@ -1,8 +1,13 @@
 #!/bin/bash
 
+# This file is a mess.  It needs major refactoring.  One day, if I have some time...
+# -- Hans Deragon (hans@deragon.biz), 2022-09-25 08:14:51 EDT
+
 SCRIPT_NAME="${BASH_SOURCE[0]/*\/}" # Basename, efficient form.
 SCRIPT_PATH_ABS="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" # Fetch real directory, not symlink.  Spaces are well handled.
 LOGFILE="${SCRIPT_PATH_ABS}/${SCRIPT_NAME}.log"
+
+PACKAGE_DIR="${SCRIPT_PATH_ABS}/packages"
 
 usage()
 {
@@ -71,24 +76,52 @@ EOM
 
 buildpackage()
 {
+  local DISTRO_NAME="${1/\/*/}"
+  local DISTRO_VERSION="${1/*\//}"
+  shift;
+  if [ "${DISTRO_VERSION}" == "${DISTRO_NAME}" ]; then
+    # No version provided.  Setting to nothing.
+    DISTRO_VERSION=""
+  else
+    # Adding seperator
+    DISTRO_VERSION="-${DISTRO_VERSION}"
+  fi
+
+  local LOCAL_PACKAGE_DIR="${PACKAGE_DIR}"
+
+  mkdir -p "${LOCAL_PACKAGE_DIR}"
+  cd       "${LOCAL_PACKAGE_DIR}"
+
   #FPM_DEBUG_OPTIONS="--debug-workspace"
-  STDOUT=$(set +e; fpm ${FPM_DEBUG_OPTIONS} \
-    --force \
-    --input-type dir \
-    --exclude DEBIAN \
-    --version         "${PACKAGE_VERSION}" \
-    --architecture    "${ARCHITECTURE}" \
-    --maintainer      "${MAINTAINER}" \
-    --description     "${DESCRIPTION_LONG}" \
-    --license         "${LICENCE}" \
-    --url             "${URL}" \
-    $@; set -e)
-  FILENAME=$(echo -e "${STDOUT}" | perl -ne 'print if s/.*\:path=>"(.*?\.(deb|rpm))".*/\1/g')
-  #echo "\${FILENAME} ${FILENAME}"
-  if [ -z "${FILENAME}" ]; then
-    echo "BUG:  \${FILENAME} is empty.  Aborting."
+  STDOUT="$(set +e; fpm ${FPM_DEBUG_OPTIONS} \
+    --force                                  \
+    --input-type dir                         \
+    --exclude         "DEBIAN"               \
+    --version         "${PACKAGE_VERSION}"   \
+    --architecture    "${ARCHITECTURE}"      \
+    --maintainer      "${MAINTAINER}"        \
+    --description     "${DESCRIPTION_LONG}"  \
+    --license         "${LICENCE}"           \
+    --url             "${URL}"               \
+    $@ 2>&1)"
+
+  #echo -e "STDOUT:  ${STDOUT}"
+  if (( $? > 0 )); then
+    echo -e "ERROR:  ${STDOUT}"
     exit 1
   fi
+
+  FILENAME_ORG="$(echo -e "${STDOUT}" | sed -rn "s/.*:path=>\"(.*?)\.(deb|rpm)\".*/\1.\2/gp")"
+
+  #echo "\${FILENAME}=>>${FILENAME}<<"
+  if [ -z "${FILENAME_ORG}" ]; then
+    echo "BUG:  \${FILENAME_ORG} is empty.  Aborting."
+    exit 1
+  fi
+
+  FILENAME="$(echo -e "${STDOUT}" | sed -rn "s/.*:path=>\"(.*?)\.(deb|rpm)\".*/\1-${DISTRO_NAME}${DISTRO_VERSION}.\2/gp")"
+
+  mv "${FILENAME_ORG}" "${FILENAME}"
 }
 
 
@@ -99,19 +132,19 @@ build_daemon_dir() {
   rm -rf "${BUILD_DAEMON_DIR}"
   mkdir -p "${BUILD_DAEMON_DIR}"
   rsync -ar "${BUILD_GENERIC_DIR}/"* "${BUILD_DAEMON_DIR}/." \
-    --delete \
-    --exclude '**/glade/'                 \
-    --exclude '**/polkit-1/'              \
-    --exclude '**/pixmaps/'               \
-    --exclude '**/autopoweroff.desktop'   \
-    --exclude '**/autopoweroff-gui'       \
-    --exclude 'autopoweroff.rc-status'    \
-    --exclude '**/pam.d/'                 \
-    --exclude '**/etc/security/'          \
-    --exclude '*-uninstall'               \
+    --delete                                                 \
+    --exclude '**/glade/'                                    \
+    --exclude '**/polkit-1/'                                 \
+    --exclude '**/pixmaps/'                                  \
+    --exclude '**/autopoweroff.desktop'                      \
+    --exclude '**/autopoweroff-gui'                          \
+    --exclude 'autopoweroff.rc-status'                       \
+    --exclude '**/pam.d/'                                    \
+    --exclude '**/etc/security/'                             \
+    --exclude '*-uninstall'                                  \
     --prune-empty-dirs
 
-  mv "${BUILD_DAEMON_DIR}/usr/share/doc/autopoweroff" "${BUILD_DAEMON_DIR}/usr/share/doc/autopoweroff-daemon"
+  mv "${BUILD_DAEMON_DIR}/usr/share/doc/autopoweroff"  "${BUILD_DAEMON_DIR}/usr/share/doc/autopoweroff-daemon"
   mv "${BUILD_DAEMON_DIR}/etc/init.d/autopoweroff.lsb" "${BUILD_DAEMON_DIR}/etc/init.d/autopoweroff"
 }
 
@@ -151,7 +184,7 @@ list_deb_info()
 }
 
 
-build_daemon_deb()
+build_daemon_deb_dir()
 {
   rm -rf "${GENERATED_DIR}/build-daemon-deb"
   mkdir -p "${GENERATED_DIR}/build-daemon-deb"
@@ -161,27 +194,88 @@ build_daemon_deb()
     --exclude "*.redhat" \
     --prune-empty-dirs   \
     "${GENERATED_DIR}/build-daemon/"* "${GENERATED_DIR}/build-daemon-deb"
+}
 
-  eval buildpackage --chdir "${GENERATED_DIR}/build-daemon-deb" \
-    --name \"${PACKAGE_NAME}\" \
-    --depends python3 \
-    --depends python3-pyinotify \
-    --depends python3-psutil \
+
+build_ubuntu_20.04()
+{
+  # Daemon Build
+  eval buildpackage                              \
+    "ubuntu/20.04"                               \
+    --chdir  "${GENERATED_DIR}/build-daemon-deb" \
+    --name    \"${PACKAGE_NAME}-daemon\"         \
+    --depends python3                            \
+    --depends python3-pyinotify                  \
+    --depends python3-psutil                     \
+    --output-type deb
+
+  list_deb_info "${FILENAME}"
+
+  # GUI Build
+  eval buildpackage                       \
+    "ubuntu/20.04"                        \
+    --chdir  "${GENERATED_DIR}/build-gui" \
+    --name    \"${PACKAGE_NAME}-gui\"     \
+    --depends \"${PACKAGE_NAME}-daemon\"  \
+    --depends python3                     \
+    --depends python-gi                   \
+    --depends policykit-1                 \
     --output-type deb
 
   list_deb_info "${FILENAME}"
 }
 
-
-# Build generic deb, works on Ubuntu 20.04.
-build_gui_deb()
+build_ubuntu_22.04()
 {
-  eval buildpackage --chdir "${GENERATED_DIR}/build-gui" \
-    --name \"${PACKAGE_NAME}-gui\" \
-    --depends autopoweroff \
-    --depends python3 \
-    --depends python-gi \
-    --depends policykit-1 \
+  # Daemon Build
+  eval buildpackage                                 \
+    "ubuntu/22.04"                                  \
+    --chdir   \"${GENERATED_DIR}/build-daemon-deb\" \
+    --name    \"${PACKAGE_NAME}-daemon\"            \
+    --depends python3                               \
+    --depends python3-pyinotify                     \
+    --depends python3-psutil                        \
+    --output-type deb
+
+  list_deb_info "${FILENAME}"
+
+  # GUI Build
+  eval buildpackage                          \
+    "ubuntu/22.04"                           \
+    --chdir   \"${GENERATED_DIR}/build-gui\" \
+    --name    \"${PACKAGE_NAME}-gui\"        \
+    --depends \"${PACKAGE_NAME}-daemon\"     \
+    --depends python3                        \
+    --depends python-gi-dev                  \
+    --depends policykit-1                    \
+    --output-type deb
+
+  list_deb_info "${FILENAME}"
+}
+
+build_popos_22.04()
+{
+  # Daemon Build
+  eval buildpackage                                 \
+    "popos/22.04"                                   \
+    --chdir   \"${GENERATED_DIR}/build-daemon-deb\" \
+    --name    \"${PACKAGE_NAME}-daemon\"            \
+    --depends python3                               \
+    --depends python3-pyinotify                     \
+    --depends python3-psutil                        \
+    --output-type deb
+
+  list_deb_info "${FILENAME}"
+
+  # GUI Build
+  eval buildpackage                          \
+    "popos/22.04"                            \
+    --chdir   \"${GENERATED_DIR}/build-gui\" \
+    --name    \"${PACKAGE_NAME}-gui\"        \
+    --depends \"${PACKAGE_NAME}-daemon\"     \
+    --depends python3                        \
+    --depends python-gi-dev                  \
+    --depends policykit-1                    \
     --output-type deb
 
   list_deb_info "${FILENAME}"
@@ -190,14 +284,30 @@ build_gui_deb()
 
 # Build specific deb for Linux Mint 20.3.
 # See:  https://github.com/deragon/autopoweroff/issues/32
-build_gui_linuxmint()
+# List of all version of Linux Mint at:  https://linuxmint.com/download_all.php
+build_gui_linuxmint_20.3()
 {
-  eval buildpackage --chdir "${GENERATED_DIR}/build-gui" \
-    --name \"${PACKAGE_NAME}-gui-linuxmint\" \
-    --depends autopoweroff \
-    --depends python3 \
-    --depends python3-gi \
-    --depends policykit-1 \
+  # Daemon Build
+  eval buildpackage                                 \
+    "mint/22.3"                                     \
+    --chdir   \"${GENERATED_DIR}/build-daemon-deb\" \
+    --name    \"${PACKAGE_NAME}-daemon\"            \
+    --depends python3                               \
+    --depends python3-pyinotify                     \
+    --depends python3-psutil                        \
+    --output-type deb
+
+  list_deb_info "${FILENAME}"
+
+  # GUI Build
+  eval buildpackage                          \
+    "mint/20.3"                              \
+    --chdir   \"${GENERATED_DIR}/build-gui\" \
+    --name    \"${PACKAGE_NAME}-gui\"        \
+    --depends \"${PACKAGE_NAME}-daemon\"     \
+    --depends python3                        \
+    --depends python3-gi                     \
+    --depends policykit-1                    \
     --output-type deb
 
   list_deb_info "${FILENAME}"
@@ -236,8 +346,11 @@ build_daemon_rpm()
   mv autopoweroff.redhat autopoweroff
   cd -
 
-  eval buildpackage --chdir "${GENERATED_DIR}/build-daemon-rpm" \
-    --name \"${PACKAGE_NAME}\" \
+  set -x
+  eval buildpackage \
+    "fedora" \
+    --chdir "${GENERATED_DIR}/build-daemon-rpm" \
+    --name \"${PACKAGE_NAME}-daemon\" \
     --depends python3 \
     --depends python-inotify \
     --depends python3-psutil \
@@ -249,7 +362,9 @@ build_daemon_rpm()
 
 build_gui_rpm()
 {
-  eval buildpackage --chdir "${GENERATED_DIR}/build-gui" \
+  eval buildpackage \
+    "fedora" \
+    --chdir "${GENERATED_DIR}/build-gui" \
     --name \"${PACKAGE_NAME}-gui\" \
     --depends python3 \
     --depends python3-gobject-base \
@@ -257,6 +372,7 @@ build_gui_rpm()
     --depends polkit \
     --depends iputils \
     --output-type rpm
+
   list_rpm_info "${FILENAME}"
 }
 
@@ -264,6 +380,7 @@ build_gui_rpm()
 # PROCESSING
 # ────────────────────────────────────────────────────────────────────────────
 {
+  rm -rf "${PACKAGE_DIR}"
 
   SCRIPT_PATH_ABS="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" # Fetch real directory, not symlink.  Spaces are well handled.
   cd "${SCRIPT_PATH_ABS}"
@@ -322,8 +439,10 @@ build_gui_rpm()
   build_gui_rpm
 
   # Deb building
-  build_daemon_deb
-  build_gui_deb        # Generic deb, works on Ubuntu 20.04.
-  build_gui_linuxmint  # Specific for Linux Mint.
+  build_daemon_deb_dir
+  build_ubuntu_20.04
+  build_ubuntu_22.04
+  build_popos_22.04
+  build_gui_linuxmint_20.3
 
 } 2>&1 | tee "${LOGFILE}"
